### ISSUE TITLE
Error updating Test: test with id xxxx not found!

### ISSUE THREAD

**Issue by AjaxOdessa** [Xray-App/xray-cloud-mig#1]
Hello,

I know this is unsupported product, but I think it will be great to have documented found issues/problems.
At the moment I'm struggling with the error "Error updating Test: test with id 123456 not found!". The problem is that both on-prem and Cloud Jira have issue with id 123456 which I can access and edit and it is totally unclear where exactly the error is happening. It will be great to have a better clarity in the error message on where exactly an issue isn't found or at least which resource was queried when this error happened.

**Comment by bitcoder** [comment]
Hi @AjaxOdessa , were you able to solve your issue?

**Comment by ajaxodesa** [comment]
Yes. I’ve add some extra logging and found that error happens on the post to Xray GraphQL. The data was put of sync so I had to reindex few projects.
